# Generated by Django 4.2 on 2023-04-19 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="start_date",
        ),
        migrations.AddField(
            model_name="appointment",
            name="begin_at",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="appointment",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="appointment",
            name="finish_at",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
