# Generated by Django 4.2 on 2023-04-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("booked", "Booked"), ("cancel", "Cancel")],
                default="booked",
                max_length=255,
            ),
        ),
    ]
