# Generated by Django 4.2 on 2023-04-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_appointment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[("Booked", "Booked"), ("Cancel", "Cancel")],
                default="Booked",
                max_length=255,
            ),
        ),
    ]
