# Generated by Django 4.2 on 2023-04-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_remove_appointment_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="begin_at",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="finish_at",
            field=models.TimeField(),
        ),
    ]
