# Generated by Django 4.2 on 2023-04-18 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
    ]
