# Generated by Django 4.2 on 2023-04-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surgeon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surgeon",
            name="specialty",
            field=models.CharField(
                choices=[
                    ("Plastic", "Plastic"),
                    ("Orthopaedic", "Orthopaedic"),
                    ("Ophthalmology Surgery", "Ophthalmology Surgery"),
                    ("Generalist", "Generalist"),
                ],
                default="Generalist",
                max_length=255,
            ),
        ),
    ]
