# Generated by Django 4.2 on 2023-04-18 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("surgeon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surgeon",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="surgeon_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
